### ISSUE TITLE
New 'switch' element requested by mobile team

### ISSUE THREAD

**Issue by KateMacdonald** [WestpacCXTeam/GUI-source#114]
Some ideas

![image](https://cloud.githubusercontent.com/assets/6667337/9053924/e485c0a4-3abe-11e5-8116-f22d5a936f06.png)

**Comment by dominikwilkowski** [comment]
Added first draft [here](http://westpaccxteam.github.io/GUI-source/switches/1.0.0/tests/WBC/) via 99e1f3d21ae26bf005abddabf7a7b83d4c80058e

Responsive sizes to follow
