### ISSUE TITLE
Icons in dynamic DOM

### ISSUE THREAD

**Issue by dominikwilkowski** [WestpacCXTeam/GUI-source#144]
How to run grunticon in an SPA?

This issue is linked with filamentgroup/grunticon#258 and still open.
Until grunticon has this issue open let me suggest some way to get this to work for now:

## Angular solution 1

```JS
(function guiGrunticonsEmbedDirective() {
    'use strict';
    var componentsModule = angular.module('gui.ng.components.grunticonEmbed', []);
    componentsModule.directive('grunticonEmbed', grunticonEmbed);

    function grunticonEmbed() {
        var directive = {
            restrict: 'A',
            scope: false,
            link: linkFunc
        };

        return directive;

        function linkFunc() {
            grunticon.embedIcons(grunticon.getIcons(grunticon.getCSS(grunticon.href)));
        }
    }
})();
```

## Angular solution 2

https://gist.github.com/navad/c6da12424ef9bc573700 (not sure about that one)

If you have more let us know.

**Comment by dominikwilkowski** [comment]
There is also a cool way to change the color by using `-webkit-mask-image` in CSS. This also should be an option to be considered here.

**Comment by navad** [comment]
Gist updated with our latest version (more in the comments section)

**Comment by dominikwilkowski** [comment]
nice work @navad 
looks great

**Comment by dominikwilkowski** [comment]
There is effort in writing an angular GUI which is also tackling the same issue.
For reference see more here: WestpacCXTeam/GUI-angular#1

**Comment by dominikwilkowski** [comment]
Just for future references, this is the unminified version of the loader script for grunticon:
https://github.com/filamentgroup/grunticon-lib/blob/master/static/grunticon.loader.js

**Comment by dominikwilkowski** [comment]
Just an FYI:
A new proposed svg system will be implemented soonish. Please have a look and submit any concerns. We expect it to solve this issue.

https://github.com/WestpacCXTeam/GUI-source/issues/209

**Comment by dominikwilkowski** [comment]
Closing due to the fact that we already have a working directive for Angular and are also moving away from grunticon via #209

**Comment by markhbucknell** [comment]
For anyone else that is looking for a solution for Angular (Tested on v6), I had to create this to get this to work: https://gist.github.com/markhbucknell/19edab47bac1fa3bda4a2cbc65b584b9 

I still had to style like this
```
.icon.icon-info svg path
  fill: #0074c4
```
This is a bit of a quick solution, there may be something better out there
