### ISSUE TITLE
Support for Foreign language like Vietnamese

### ISSUE THREAD

**Issue by ankitsusheel** [WestpacCXTeam/GUI-source#146]
Currently few pages which contains foreign language are working unexpectedly and some letters are not displaying in H1

https://www.stgeorge.com.au/personal/solutions/new-to-australia/vietnamese

**Comment by dominikwilkowski** [comment]
Thanks for reporting @imshitu 

We recommend to fallback to a font-family without the webfont so either remove the 'roboto' font string or remove the webfont itself on that page. The later is preferred if you are able to.

This is a very intriguing problem you got there though :+1:

**Comment by dominikwilkowski** [comment]
I added this question to the FAQs. Thanks for that again. We will updated this when new information come in.

**Comment by dominikwilkowski** [comment]
We are still investigating this actually so let me reopen :)

Right now we are thinking to remove the roboto web-font all together. This would mean for body text the system font for each OS will be used. That makes sense as those font's are explicitly tuned for each system.

the font-family would then become something like:

`-apple-system, ".SFNSText-Regular", "San Francisco", "Roboto", "Segoe UI", "Helvetica Neue", "Lucida Grande", sans-serif;`

**Comment by oksushi** [comment]
If you were to keep with the brand font, you could also create an `extended` version, that contained the glyphs excluded from the main set. You can then load these as required for language–specific pages, or across an entire site.

You can do this with [Unicode Range Subsetting](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/webfont-optimization#unicode-range-subsetting)

**Comment by dominikwilkowski** [comment]
Yeah that's a great idea for the brand-font. I am not sure the dragon font built for St.George even has those characters in the first place.

Let's find out. :)

**Comment by dominikwilkowski** [comment]
Testing of the above mentioned font-family
`-apple-system, ".SFNSText-Regular", "San Francisco", "Roboto", "Segoe UI", "Helvetica Neue", "Lucida Grande", sans-serif;`

resulted in all devices supporting all font-weights with the notable exception of our own windows phone that only displays `bold` and `normal`.

In light of the usage of those devices only being inside Westpac I am inclined to disregard them. Does anyone think differently?
