### ISSUE TITLE
GUI Blender error

### ISSUE THREAD

**Issue by jharris-westpac** [WestpacCXTeam/GUI-source#148]
After creating one blend, I have gone back and tried to make a new blend and get this error.

http://gel.westpacgroup.com.au/GUI/WBC/blender/

```shell
http://128.199.237.107:8080/blender
TypeError: Cannot read property 'versions' of undefined
   at FilesIteratePost (/var/www/html/GUI/file-server/server.js:245:41)
   at Array.forEach (native)
   at Object.FilesGetPost [as getPost] (/var/www/html/GUI/file-server/server.js:234:23)
   at Object.FilesInit [as init] (/var/www/html/GUI/file-server/server.js:189:13)
   at PostListener (/var/www/html/GUI/file-server/server.js:74:15)
   at Layer.handle [as handle_request] (/var/www/html/GUI/file-server/node_modules/express/lib/router/layer.js:95:5)
   at next (/var/www/html/GUI/file-server/node_modules/express/lib/router/route.js:131:13)
   at Route.dispatch (/var/www/html/GUI/file-server/node_modules/express/lib/router/route.js:112:3)
   at Layer.handle [as handle_request] (/var/www/html/GUI/file-server/node_modules/express/lib/router/layer.js:95:5)
   at /var/www/html/GUI/file-server/node_modules/express/lib/router/index.js:277:22
```

**Comment by dominikwilkowski** [comment]
Hey @jharris-westpac 

Can you post the version URL? Thanks.

**Comment by jharris-westpac** [comment]
Cant get the URL but got a reproducible form post extract. It seems to happen if I do not select the JavaScript components, but select everything else. 

Form post data:
module-_colors=1.0.0&module-_fonts=1.0.0&module-_text-styling=1.0.0&module-text-extensions=1.0.0&tick-text-extensions=on&module-_grid=1.0.0&module-responsive-margins=1.0.0&tick-responsive-margins=on&module-responsive-toggles=1.0.0&tick-responsive-toggles=on&module-_javascript-helpers=1.0.0&module-accessibility-helpers=1.0.0&tick-accessibility-helpers=on&module-alerts=1.0.2&tick-alerts=on&module-badges=1.0.0&tick-badges=on&module-labels=1.0.0&tick-labels=on&module-progress-bars=1.0.0&tick-progress-bars=on&module-breadcrumbs=1.0.0&tick-breadcrumbs=on&module-paginations=1.0.0&tick-paginations=on&module-buttons=1.0.2&tick-buttons=on&module-switches=1.0.0&tick-switches=on&module-checkboxes=1.0.1&tick-checkboxes=on&module-input-addons=1.0.1&tick-input-addons=on&module-input-fields=1.0.0&tick-input-fields=on&module-input-groups=1.0.0&tick-input-groups=on&module-radios=1.0.1&tick-radios=on&module-icons-base=1.0.0&tick-icons-base=on&module-icons-group01=1.0.0&tick-icons-group01=on&module-icons-group02=1.0.0&tick-icons-group02=on&module-icons-group03=1.0.0&tick-icons-group03=on&module-icons-group04=1.0.0&tick-icons-group04=on&module-icons-group05=1.0.0&tick-icons-group05=on&module-icons-group06=1.0.0&tick-icons-group06=on&module-icons-group07=1.0.0&tick-icons-group07=on&module-icons-group08=1.0.0&tick-icons-group08=on&module-icons-group09=1.0.0&tick-icons-group09=on&module-icons-group10=1.0.0&tick-icons-group10=on&module-icons-group11=1.0.0&tick-icons-group11=on&module-icons-group12=1.0.1&tick-icons-group12=on&module-icons-group13=1.0.0&tick-icons-group13=on&module-icons-group14=1.0.0&tick-icons-group14=on&module-icons-group15=1.0.0&tick-icons-group15=on&module-icons-group16=1.0.0&tick-icons-group16=on&module-images=1.0.0&tick-images=on&module-responsive-embeds=1.0.0&tick-responsive-embeds=on&module-list-groups=1.0.0&tick-list-groups=on&module-lists=1.0.0&tick-lists=on&module-logos=1.0.0&tick-logos=on&module-symbols=1.0.0&tick-symbols=on&module-modals=1.0.1&module-popovers=1.0.1&module-tooltips=1.0.1&module-panels=1.0.0&tick-panels=on&module-tabcordions=1.0.1&module-wells=1.0.0&tick-wells=on&module-tables=1.0.0&tick-tables=on&includeJquery=no&includeUnminifiedJS=no&includeLess=no&includeBond=no&brand=WBC

**Comment by jharris-westpac** [comment]
I am now getting this error every time if I select everything. This is preventing me from continuing my work unfortunately as I am not able to download GUI at all. Any ETA on a fix?

**Comment by dominikwilkowski** [comment]
@jharris-westpac Bug fixed. Make sure you flush your localStorage and refresh the page.
