### ISSUE TITLE
I Love Pie's

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-source#149]
Preloaders put the Pie back

**Comment by dominikwilkowski** [comment]
http://codepen.io/abalozz/pen/ukLCf

Need to think of a fallback though... icons-group17?!

**Comment by oksushi** [comment]
Shouldn’t this be SVG?

**Comment by dominikwilkowski** [comment]
Why? I think the hard part is to manage the fallback. Obviously the Peng can't be animated and anyhow a browser that doesn't support SVG doesn't have animations so the only fallback I see is a gif. Which is what we have provided in 'icons-group1'. 
Even with SVG it's going to be hard to replicate this effect I found.

Love to get feedback though. 


--

Dominik Wilkowski

M\\  +61 432 717 489
W\\  DOMINIK-WILKOWSKI.COM
E\\   HI@DOMINIK-WILKOWSKI.COM

**Comment by dominikwilkowski** [comment]
We looked into this and the fallback is going to be fine but the animation with a background pattern won't do even in Safari or Firefox...

http://codepen.io/dominikwilkowski/pen/jbjxav

Better ideas? Animating an SVG? How can we fallback? I am not aware of an SVG element that can paint half circles?

**Comment by oksushi** [comment]
http://loading.io comes to mind — they use SVG with an animated gif fallback.

**Comment by justinspencer** [comment]
Not quite sure what you want me to do here. If it can't be built I guess we should close the issue.
