### ISSUE TITLE
Smaller checkbox and radio buttons

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-source#151]
Need to have an additional size for checkbox and radio buttons. They are currently 32px need a smaller size 24px. No idea how we're going to do this.

**Comment by dominikwilkowski** [comment]
I am still investigating how to avoid to include several artworks just for different sizes. The border around the checkboxes and radios is 1 pixel which means it cannot be shrunken... Moving the border into a pseudo element will break vertical-alignment.

Ideas welcome

**Comment by justinspencer** [comment]
Here are the svgs for the checkbox and radio buttons at 24px
They are straight out of an Illustrator export so they will need a bit of love.
All visual design assets in the starter pack have been updated.

[svgs.zip](https://github.com/WestpacCXTeam/GUI-source/files/347254/svgs.zip)

**Comment by dominikwilkowski** [comment]
So we now only give the 24px option. Just to clarify this here.
