### ISSUE TITLE
Switch shadows

### ISSUE THREAD

**Issue by domkipps** [WestpacCXTeam/GUI-source#155]
Would it be crisper to not have the drop shadows on scrubber/handle of the dark versions of the switch handle. They can look a little dirty, especially on some brands.

![switch](https://cloud.githubusercontent.com/assets/183320/11354958/dee898ea-92a4-11e5-96f8-a91d3fbe8132.png)

**Comment by justinspencer** [comment]
Hi Dom, Yep we noticed that too. Dirty, dirty buttons. I'll assign it to a milestone.
Thanks.

**Comment by domkipps** [comment]
Great! Nice work btw, wish we had them switches a few months back!
