### ISSUE TITLE
St.George text colour needs changing

### ISSUE THREAD

**Issue by dominikwilkowski** [WestpacCXTeam/GUI-source#158]
Colour to be provided

**Comment by justinspencer** [comment]
Text new text colour is  #333333
This colour is only used for paragraph, small, strong, emphasis and lead text. Headings stay the same dark green. Buttons also stay the same dark green.

**Comment by justinspencer** [comment]
Just looking into this and there may be some accessibility issues with #333. Also adding a new colour to the palette will break the system we currently have where Text (colour F) is the default colour for text in all brands. If we change colour F in the St.George GUI there will be no reference to the dark green.

**Comment by dominikwilkowski** [comment]
@justinspencer Is this still something you want to do? If this is old please close. :)
