### ISSUE TITLE
Adding uberbutton to GUI

### ISSUE THREAD

**Issue by dominikwilkowski** [WestpacCXTeam/GUI-source#159]

**Comment by dominikwilkowski** [comment]
<img width="971" alt="screen shot 2015-12-02 at 11 23 31 am" src="https://cloud.githubusercontent.com/assets/1266923/11518619/35001670-98e7-11e5-852c-e08b73c09b9f.png">

**Comment by jonnystening** [comment]
Is this still on the cards @justinspencer?

**Comment by justinspencer** [comment]
This is more of a bespoke form component. Not sure if people actually use it that much. @KateMacdonald your call.

**Comment by KateMacdonald** [comment]
Agreed, this is bespoke. Doesn't need GUI-fication.



Kate MacDonald
Senior Design Manager, Experience Design & Delivery

W 0435 409 891
ktmacdonald@westpac.com.au

Westpac Group
L22, Tower 2 Barangaroo Ave
Barangaroo NSW 2000 Australia


-------- Original message --------

**Comment by KateMacdonald** [comment]
I don't think we need it. Agree that it's too bespoke.



Kate MacDonald
Senior Design Manager, Experience Design & Delivery

W 0435 409 891
ktmacdonald@westpac.com.au

Westpac Group
L22, Tower 2 Barangaroo Ave
Barangaroo NSW 2000 Australia


-------- Original message --------

**Comment by jonnystening** [comment]
Closing this in the name of bespoke 🏁
