### ISSUE TITLE
Unminified version of gui.min.js

### ISSUE THREAD

**Issue by dowda** [WestpacCXTeam/GUI-source#161]
Could you please provide an unminified version of gui.min.js

We need to see what it does so we can decide if we want to use  it

Regards
Andrew

**Comment by dominikwilkowski** [comment]
Hi @dowda 

Thanks for the request. At the bottom of the [blender page](http://gel.westpacgroup.com.au/GUI/STG/blender/) you can find an option to include the unminified JavaScript in your blend.

<img width="605" alt="screen shot 2015-11-25 at 1 21 21 pm" src="https://cloud.githubusercontent.com/assets/1266923/11386664/938d1dde-9377-11e5-9c32-563ae1a74e37.png">

If you select "YES" here and download the blend the zip file will include a "js" folder inside the "source" folder:

```shell
.
├── assets
│   ├── css
│   │   ├── [files]
│   ├── font
│   │   └── [files]
│   ├── img
│   │   └── [files]
│   └── js
│       └── gui.min.js       # <-- minified gui js file
├── index.html
└── source
    ├── js                   # <-- unminified js files
    │   ├── 020-core.js      # <-- core js file
    │   ├── alerts.js
    │   ├── buttons.js
    │   ├── modals.js
    │   ├── popovers.js
    │   ├── tabcordions.js
    │   └── tooltips.js
    └── less
        └── [files]
```

In there you'll find all unminified JavaScript files complete with comments that you selected in your blend. All the `gui.min.js` file is is a minification of those files in alphabetical order (hence the `020-` prefix for the core file).

I hope this helps. Let me know if we missed something or you got questions.

Cheers
