### ISSUE TITLE
logos in symbols duplication

### ISSUE THREAD

**Issue by dowda** [WestpacCXTeam/GUI-source#165]
Noticed there are duplication of logos in symbols, is there a reason for this?

see st.george 
http://gel.westpacgroup.com.au/GUI/STG/symbols/

.symbol .symbol-logo-tablet
.symbol .symbol-logo-phone
.symbol .symbol-logo-alt

.logo .logo-stg-tablet
.logo .logo-stg-alt
.logo .logo-stg-phone

cheers
Humphrey B. Bear

**Comment by dominikwilkowski** [comment]
Hey Dowie

The `symbols` module gives you your current brand logo so in a multi-brand environment something like:
`<span class="symbol symbol-logo-phone"></span>` will be the logo of whatever brand you're developing in. No HTML changes between a brand build.

But sometimes you want all logos like in a project like locate-us. For those we got the `logos` module. Those classes then have to be specific to point directly to a brand logo and don't change between brands. Still no changes between brand builds.

Hope this clears it up. Reopen the issue if it doesn't.
