### ISSUE TITLE
Why do we need two selectors for everything in symbols css?

### ISSUE THREAD

**Issue by dowda** [WestpacCXTeam/GUI-source#167]
Why do we need two selectors for everything?   increases file size and ads to ie9 selector limit

see symbols.data.png.css, symbols.data.svg.css,  symbols.data.fallback.css

.icon-credit-card,
.symbol-credit-card

.icon-growth,
.symbol-growth

.icon-limit,
.symbol-limit

Regards
Chong

**Comment by dominikwilkowski** [comment]
Hey Dowie

Good question. We added those selectors to stay compatible with GUI 1. At some time we might consider deprecating those. You're welcome to start a push for better class names. I'm all for it! :)

**Comment by dowda** [comment]
which will we use going forward?

**Comment by dominikwilkowski** [comment]
Both will be maintained as both have very different use cases. You chose what you use in the blender.
