### ISSUE TITLE
GEL2 chevron not working on IE 10, 9 and 8

### ISSUE THREAD

**Issue by sachinsinghi** [WestpacCXTeam/GUI-source#169]
IE10: 
![image](https://cloud.githubusercontent.com/assets/3579653/11647070/fb616f6a-9db7-11e5-89e9-03a2cab2e871.png)

IE9: 
![image](https://cloud.githubusercontent.com/assets/3579653/11647050/d1b712be-9db7-11e5-8bf5-40473e6243ae.png)

IE8: 
![image](https://cloud.githubusercontent.com/assets/3579653/11647060/e2fc066a-9db7-11e5-981a-16c9d9ab6583.png)

**Comment by dominikwilkowski** [comment]
Hey @sachinsinghi 

I get this:

IE9:
![screen shot 2015-12-17 at 3 35 34 pm](https://cloud.githubusercontent.com/assets/1266923/11861387/d5f2f316-a4d3-11e5-9a43-5a395676f59b.png)

IE8:
![screen shot 2015-12-17 at 3 35 21 pm](https://cloud.githubusercontent.com/assets/1266923/11861393/dac08732-a4d3-11e5-8903-c80d37a866b5.png)


So I think you might be missing the HTML boilerplate in the head of your HTML file:
```html
<!DOCTYPE html>
<!--[if lt IE 8]>
	<html class="no-js lt-ie8 lt-ie9" lang="en">
<![endif]-->
<!--[if IE 8]>
	<html class="no-js lt-ie9 ie8" lang="en">
<![endif]-->
<!--[if IE 9 ]>
	<html class="no-js ie9" lang="en">
<![endif]-->
<!--[if !(IE)]><!-->
	<html class="no-js" lang="en">
<!--<![endif]-->

<head>
etc...
```

I can't reproduce for now so please reopen if you still see this issue in [the docs](http://gel.westpacgroup.com.au/GUI/STG/lists/#lists)
