### ISSUE TITLE
New Wheelchair accessibility icon to be added

### ISSUE THREAD

**Issue by KateMacdonald** [WestpacCXTeam/GUI-source#170]
![image](https://cloud.githubusercontent.com/assets/6667337/11673383/725a1996-9e6c-11e5-8153-aabdd195b680.png)

**Comment by dominikwilkowski** [comment]
What about `icon-accessibility`? Will that be removed or what should this icon be called?

**Comment by KateMacdonald** [comment]
We can just call the new one 'wheelchair'.

Sent from my iPhone

On 9 Dec 2015, at 12:04 PM, Dominik Wilkowski <notifications@github.com<mailto:notifications@github.com>> wrote:


What about icon-accessibility? Will that be removed or what should this icon be called?

�
Reply to this email directly or view it on GitHub<https://github.com/WestpacCXTeam/GUI-source/issues/170#issuecomment-163074098>.

Confidential communication
Westpac Banking Corporation (ABN 33 007 457 141)
Westpac Institutional Bank is a division of Westpac Banking Corporation

**Comment by justinspencer** [comment]
Attached are 2 svgs I've also added the bank icon. These are generated using Illustrators new svg export filters. There are several options to choose from this was just the default setting.

[icons.zip](https://github.com/WestpacCXTeam/GUI-source/files/63365/icons.zip)

**Comment by justinspencer** [comment]
Here are 4 additional svg icons:
bank.svg
key-hole.svg
news.svg
wheelchair.svg
Not sure which groups to put them in. @KateMacdonald
[svg-icons.zip](https://github.com/WestpacCXTeam/GUI-source/files/64724/svg-icons.zip)

**Comment by justinspencer** [comment]
NEWS FLASH!!
Please scrap the news icon. Kate thinks it's stupid.

**Comment by justinspencer** [comment]
Bank - Group 5
Key-hole - Group 5
Wheelchair - Group 9

**Comment by dominikwilkowski** [comment]
Group5 is full... I'll start a new group with those two icons then
