### ISSUE TITLE
Soft tabcordion not working

### ISSUE THREAD

**Issue by Hakim2014** [WestpacCXTeam/GUI-source#171]
When switching the tab, "is-active" class is not added to switched/active tab.

![image](https://cloud.githubusercontent.com/assets/8450333/11797014/2975ef46-a314-11e5-97c5-881dad1f63a0.png)

**Comment by dominikwilkowski** [comment]
Hey @Hakim2014 

Thanks for the report. I need more info on this. What's the console output? (activate by running `GUI.DEBUG = true;` right after the `gui.min.js`), Where do you include the js? have you got all `js-` classes in your HTML?

**Comment by dominikwilkowski** [comment]
Also what do you mean by "When switching the tab"? Is the tabcordion added into the DOM dynamically? If so are you running the `GUI.tabcordion.render();` method?

**Comment by Hakim2014** [comment]
Hi Dom,

I am testing the softaccordian on http://thewestpacgroup-gel.io/GUI/STG/containers/

I have enabled GUI debug in console GUI.DEBUG = true; the result is 

![image](https://cloud.githubusercontent.com/assets/8450333/11798042/80576d9c-a31b-11e5-86a1-f78e9ad38ea5.png)


Infact any of the tabs are getting active on click on the gel site.

Let me know if you need more information

**Comment by dominikwilkowski** [comment]
So all tabs are getting the active state? That would be correct wouldn't it be? Sorry I am missing what it is that's not working. I just tested again the very same page on desktop and mobile and all works correctly?

Is it a browser problem? What are you checking in? What do you expect to happen and what actually happens?

Thanks so much for taking the time :)


--

Dominik Wilkowski

M\\  +61 432 717 489
W\\  DOMINIK-WILKOWSKI.COM
E\\   HI@DOMINIK-WILKOWSKI.COM

**Comment by dominikwilkowski** [comment]
For completeness: It looks like it was a browser caching issue. If it resurfaces: please reopen.

Thanks @Hakim2014
