### ISSUE TITLE
Back button icon

### ISSUE THREAD

**Issue by BastienZag** [WestpacCXTeam/GUI-source#172]
Different Westpac web app projects are using a back button (same behaviour than the browser back navigation).

I think that a back button icon will make these projects more UI consistent.

**Comment by justinspencer** [comment]
Is this what you mean? We use this in the forms work.
![screen shot 2015-12-18 at 4 12 35 pm](https://cloud.githubusercontent.com/assets/936597/11889894/489cb838-a5a2-11e5-89a6-2a0ecc194ea1.png)

**Comment by BastienZag** [comment]
This one is nice. 
Is this part of the GUI ? 
Size, color, shape

**Comment by dominikwilkowski** [comment]
We create these in CSS and don't need SVGs for them. We might add a module to address this?
@justinspencer what do you think?

**Comment by justinspencer** [comment]
Dom has changed his mind. He has now instructed me to supply the svg for this asset. I will do so promptly.

**Comment by jonnystening** [comment]
How promptly @justinspencer? ⏳

**Comment by justinspencer** [comment]
Been there, done that.

**Comment by jonnystening** [comment]
Coming soon?

**Comment by justinspencer** [comment]
In the re-vamped UI icon library there are more arrows than you can poke a stick at. Up, down left right, expand, collapse... you name it we've got it. There's an arrow for every occasion.

**Comment by jonnystening** [comment]
You beauty!

**Comment by jonnystening** [comment]
Icon will be available in Icons v2.0.0
