### ISSUE TITLE
San Francisco - Font weight not working

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-source#187]
The light 300 weight is not being implemented. The codepen example works perfectly when I change the font weight value, I can assign a weight from 100 up to 800. This is not the case in the GUI.

I also tested the font-weight property in the GUI by removing San Francisco from the font stack and assigning different font weights to text using Helvetica Neue. This worked perfectly.

**Comment by dominikwilkowski** [comment]
Doesn't work for me:
http://codepen.io/dominikwilkowski/pen/GpBmaL

On El Capitan I get:
<img width="615" alt="screen shot 2016-01-27 at 10 19 41 pm" src="https://cloud.githubusercontent.com/assets/1266923/12612018/20e9a30c-c544-11e5-8949-6c6e10edf516.png">

**Comment by justinspencer** [comment]
OMG! It's a Chrome bug!

Works perfectly in Safari. Unbelievable!

![screen shot 2016-01-27 at 10 29 42 pm](https://cloud.githubusercontent.com/assets/936597/12612274/a29a8348-c545-11e5-8b86-db80bb1c6b46.png)

**Comment by dominikwilkowski** [comment]
New fix up for texting now on same codepen:
http://s.codepen.io/dominikwilkowski/debug/GpBmaL
