### ISSUE TITLE
Panels

### ISSUE THREAD

**Issue by KateMacdonald** [WestpacCXTeam/GUI-source#19]
Where are the responsive panels???? HUH??????  :)  Please apply rules as per Wells.

Do we also want to show an example with buttons in the footer?

**Comment by dominikwilkowski** [comment]
hahaa

Turns out Justin FORGOT, I repeat:  F O R G O T  to tell me about it.

![59174256](https://cloud.githubusercontent.com/assets/1266923/7950520/0bd61ebc-09df-11e5-98f5-ca101a2fc012.jpg)

**Comment by dominikwilkowski** [comment]
I forked this issue into #24
