### ISSUE TITLE
title id="title" being added to every svg data uri

### ISSUE THREAD

**Issue by dowda** [WestpacCXTeam/GUI-source#204]
Prerequisites
-------------

* [ not tested ] Can you reproduce the problem in the [testing area of the GUI](http://westpaccxteam.github.io/GUI-source/)?
* [ not tested ] Are you running the latest version of the affected module?
* [ not tested ] Did you check if the issue already exists ([open](https://github.com/WestpacCXTeam/GUI-source/issues) or
	[closed](https://github.com/WestpacCXTeam/GUI-source/issues?q=is%3Aissue+is%3Aclosed))?

Description
-----------

title%20id%3D%22title (title id="title")   is embeded in all data uris  inside symbols.data.svg.css 

I'm assuming this is for js hooks. This should probably be something like title id="logo" and title id="house"  etc 

This is causing accsibility issue due to multiple unique ids inside of page when using data-grunt-icon-embed for more than one icon per page 

**sample**
.symbol-logo-tablet { background-image: url('data:image/svg+xml;charset=US-ASCII,%3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22utf-8%22%3F%3E%3C!DOCTYPE%20svg%20PUBLIC%20%22-%2F%2FW3C%2F%2FDTD%20SVG%201.1%2F%2FEN%22%20%22http%3A%2F%2Fwww.w3.org%2FGraphics%2FSVG%2F1.1%2FDTD%2Fsvg11.dtd%22%3E%3Csvg%20aria-labelledby%3D%22title%22%20version%3D%221.1%22%20id%3D%22Art%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20xmlns%3Axlink%3D%22http%3A%2F%2Fwww.w3.org%2F1999%2Fxlink%22%20x%3D%220px%22%20y%3D%220px%22%20%20width%3D%22180px%22%20height%3D%2265px%22%20viewBox%3D%220%200%20180%2065%22%20enable-background%3D%22new%200%200%20180%2065%22%20xml%3Aspace%3D%22preserve%22%3E%3C**title%20id%3D%22title**%22%20lang%3D%22en%22%3EWestpac%20logo%3C%2Ftitle%3E%3Crect%20opacity%3D%220%22%20fill%3D%22%23FFFFFF%22%20width%3D%22180%22%20height%3D%2265%22%2F%3E%3Cg%3E%20%3Cpath%20fill%3D%22%23D5002B%22%20d%3D%22M24.4%2C45l-6.8-20.9c-1-3.2-2.6-4.1-5.1-4.1H0c1%2C0.4%2C1.6%2C2.9%2C1.6%2C2.9l6.1%2C21c0.7%2C2.6%2C2.9%2C4%2C5.4%2C4h13.3%20%20C25.4%2C47.8%2C24.4%2C45%2C24.4%2C45%22%2F%3E%20%3Cpath%20fill%3D%22%23D5002B%22%20d%3D%22M44.6%2C45l6.8-20.9c1-3.2%2C2.6-4.1%2C5.1-4.1H69c-1%2C0.4-1.6%2C2.9-1.6%2C2.9l-6.1%2C21c-0.7%2C2.6-2.9%2C4-5.4%2C4H42.6%20%20C43.6%2C47.8%2C44.6%2C45%2C44.6%2C45%22%2F%3E%20%3Crect%20x%3D%2227%22%20y%3D%2220%22%20fill%3D%22%23D5002B%22%20width%3D%2215%22%20height%3D%2228%22%2F%3E%3C%2Fg%3E%3C%2Fsvg%3E'); background-repeat: no-repeat; }

Steps to Reproduce
------------------

1. [First Step]
2. [Second Step]
3. [and so on…]

**Expected behavior:**
[What you expected to happen]

**Actual behavior:**
[What actually happened]

Versions
--------

[What version are you using? You can add the GUI version string here if you want]

Screenshots
-----------

[Add some visual love or even a video fi you feel super dedicated]

**Comment by dominikwilkowski** [comment]
Hey @dowda 

The id attribute in the svgs are for accessibility reasons. This is a typical svg in the GUI:

```svg
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg aria-labelledby="title" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="32" height="32" viewBox="0 0 32 32">
<title id="title" lang="en">Map-pin</title>

<path fill="#004833" class="icons-background" d="M16 32l8.7-17.6c0 0-0.8 1.5 0 0 0.5-1.1 1.3-2.4 1.3-4.4 0-5-4.5-10-10-10s-10 5-10 10c0 2 0.8 3.3 1.3 4.4 0.8 1.5 0 0 0 0l8.7 17.6zM23 10c0 3.9-3.1 7-7 7s-7-3.1-7-7 3.1-7 7-7c3.9 0 7 3.1 7 7z"></path>
</svg>
```

You can see that `aria-labelledby="title"` in the `svg` tag is pointing to this `title` tag. This is so an embedded SVG can have a meaning read out in screen readers.

I get your issue though. Duplicated IDs are not ideal in HTML. I think for now we leave it like it is as duplicated IDs are not an issue in HTML5 unless you select them. Maintaining unique attributes in more than 500 svg icons will be a lot of effort and not fix any issues really. On the other hand we will never be able to guarantee that all IDs used in the GUI are unique as developers are free to make changes any time.

I hope this helps a little. I will keep this issue open and see if we can come up with something in our automation tools. I keep this low priority though.

**Comment by dominikwilkowski** [comment]
It was pointed out to me by Tony (thanks @tonytwong) that even though IDs are not a blocker in an HTML document, having the SVGs embedded into the doc will mean the IDs will point to the very first title with the ID `title` and in case we have several svgs embedded that would cause the titles to be assigned wrongly. ;)

Headspinner! We will create an automation tool to fix this bug. Don't want to loose out on our accessibility!

Thanks for bringing this up @dowda
