### ISSUE TITLE
New icons for Balance (Default, high and low)

### ISSUE THREAD

**Issue by KateMacdonald** [WestpacCXTeam/GUI-source#207]
We need icons to represent the following:

- Balance
- High balance
- Low balance

Initially this will be used in mobility to identify the different notifications that can be set up.

**Comment by justinspencer** [comment]
Darren Kirk is looking at a design for these. He is going to run them past me when they are done.

**Comment by justinspencer** [comment]
Also... Are these going to be re-used? I've never seen these labels and no one has done this before.
