### ISSUE TITLE
Highlight cell not working on XS view for :first-child

### ISSUE THREAD

**Issue by sachinsinghi** [WestpacCXTeam/GUI-source#210]
Prerequisites
-------------

* [ Yes ] Can you reproduce the problem in the [testing area of the GUI](http://westpaccxteam.github.io/GUI-source/)?
* [ Yes ] Are you running the latest version of the affected module?
* [ Yes ] Did you check if the issue already exists ([open](https://github.com/WestpacCXTeam/GUI-source/issues) or
	[closed](https://github.com/WestpacCXTeam/GUI-source/issues?q=is%3Aissue+is%3Aclosed))?

**Description:**
Highlight cell / row style does not work on xs view due to :first-chlid{border-left:0}

**Expected behavior:**
Highlight cell / row style should work on xs view

**Comment by dominikwilkowski** [comment]
Happens only on bordered table as specificity issue. Will fix in next release.
Thanks @sachinsinghi
