### ISSUE TITLE
Please add grunticon task in the grunt file :)

### ISSUE THREAD

**Issue by sachinsinghi** [WestpacCXTeam/GUI-source#212]
Hi,

Request you to please add grunticon task in the GUI source grunt file to leverage the capability to concatenate custom SVG icons into the icons css files. :)

Pretty please.

**Comment by dominikwilkowski** [comment]
Awesome idea!

I propose: in the `source` folder you can add a folder called `svgs` which are then run through grunticon and concatenate into the already delivered blend css files.
