### ISSUE TITLE
Popovers - Modals and how we show them in the docs

### ISSUE THREAD

**Issue by dominikwilkowski** [WestpacCXTeam/GUI-source#229]
The example in the iframe looks weird. What to do?

**Comment by justinspencer** [comment]
As discussed we need to implement a technique where we can demo an element or component (like a modal window or a responsive pattern) in a full screen window with no page furniture. One option is to use CSS to make the the iFrame fill the viewport. This seemed to work but we should test this on other elements that we need to demo.

**Comment by dominikwilkowski** [comment]
Merging with #257
