### ISSUE TITLE
Typography - web-fonts in the GUI

### ISSUE THREAD

**Issue by dominikwilkowski** [WestpacCXTeam/GUI-source#231]
Need to get hold of the web licence's for all brand web fonts that are used in the GUI and add them to the downloads.
BOM = Stag
STG = Dragon Bold
BT = Helvetica Neue (Not yet implemented)
Westpac = Chronicle (Not yet implemented)
BSA = Aller (Not yet implemented)

**Comment by justinspencer** [comment]
Using web-fonts in the GUI source is an issue. Licences around distribution mean we can not add font files to the download.

These are the options we've come up with so far. They are far from ideal.

1. Nuclear option. We take the web-font (and all references to the web-font) out of the GUI source but use the web-font in the docs. Projects will have to implement the web-font themselves. The web-font will not come as part of the download. This will probably result in confusion, errors and a barrage of complaints from designers, developers, brand and marketing.

2. Engage Legal. They may be able to advise us on how to distribute web-fonts to the world without breaking the licence agreement. This could take months and will probably result in a "not possible" verdict.

3. Use an obvious placeholder web-font in the GUI download and instruct developers to replace this file with the correct web-font file. This could also result in confusion, errors and a barrage of complaints from developers.

4. Remove the Typography system. Every element that could potentially use the brand font must be removed. This will restrict the GUI to core UI elements only. All elements that could potentially use a brand font would have to be removed. This will significantly reduce our product offering to marketing and brand. From a digital brand perspective the 2 key components of the GUI are the Colour system and the Typography system.

Thoughts?

**Comment by justinspencer** [comment]
Bob has come with a great idea which should work quite well.
1. We remove all web-fonts from the blender.
2. In the blend index file we provide a link to download the web-fonts from share point.
This means only developers with access to the network will be able to obtain the files.
Thank's Bob. You're a genius!

**Comment by jonnystening** [comment]
Looks like we're finally going to get BankSA's Aller webfont. Hoping to have this in the upcomming _fonts v2.0.3

@justinspencer

**Comment by jonnystening** [comment]
fixed by WestpacCXTeam/GUI_fonts@bb80580a1559d1a28623f5260668a295893b7b9c
