### ISSUE TITLE
Soft tabs - justified - Height of tabs not aligned

### ISSUE THREAD

**Issue by amitjagtap** [WestpacCXTeam/GUI-source#237]
Prerequisites
-------------

* [ - ] Can you reproduce the problem in the [testing area of the GUI](http://westpaccxteam.github.io/GUI-source/)? Yes
* [ - ] Are you running the latest version of the affected module? Yes
* [ - ] Did you check if the issue already exists ([open](https://github.com/WestpacCXTeam/GUI-source/issues) or
	[closed](https://github.com/WestpacCXTeam/GUI-source/issues?q=is%3Aissue+is%3Aclosed))?

Description
-----------

When we use "Soft tabs - justified" an increase in content of a tab title causes the tab height to increase. However, the other tabs do not pan to have the height of the tallest tab. 

**Expected behavior:**
All tabs should have equal height

**Actual behavior:**
Every tab pans to the amount of content that have
Screenshots
-----------

![image](https://cloud.githubusercontent.com/assets/4056184/14780981/0bb84932-0b23-11e6-8b5e-8b053c66dea6.png)

**Comment by dominikwilkowski** [comment]
Thanks @amitjagtap 
I was literally just writing this bug report :)
Hopefully fixed soo.

**Comment by amitjagtap** [comment]
Thanks @dominikwilkowski  looking forward for the fix :)
