### ISSUE TITLE
Remove border around modal

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-source#240]
Please remove the border around the the modal box. As the modal is always placed on a dark background there is no need for it to have a border.

Please do not remove the border-top on the modal footer.

**Comment by dominikwilkowski** [comment]
Am I assuming right only the outer border is to be removed and we keep all inner ones including the header and the footer? Also no changes to shadow...?
See result below:

<img width="644" alt="screen shot 2016-05-01 at 6 55 37 pm" src="https://cloud.githubusercontent.com/assets/1266923/14940951/693a074e-0fce-11e6-8f07-7ed707124563.png">

**Comment by justinspencer** [comment]
Perfect! Thank you Sir.

**Comment by dominikwilkowski** [comment]
No thank you good Sir!
![thank-parenthood-planned-V9i6KIwhmF2Ba](https://camo.githubusercontent.com/59eea10de04c0ddc7147df9aef87b90c437872fc/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f563969364b4977686d463242612f67697068792e676966>)
