### ISSUE TITLE
Heading tags causing confusion

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-source#251]
URGENT: The Docs suggest set styles for heading tags h1-h6. This is causing a lot of confusion for designers and developers. We need to URGENTLY remove any suggestion that heading tags are styled. As stated in the docs: h1–h6 tags are purely semantic. These are the things we do need to communicate:

1. The brand font face.
2. The body font face.
3. The range of font sizes - 42px, 36px, 30px, 24px, 18px, 16px, 14px.
5. The font weights - 300, 400, 500, 700

How these font faces, font sizes and font weights are applied is up to the designer.

**Comment by dominikwilkowski** [comment]
I agree, We need to remove the styling from the H1-6 tags and only have it on the classes.

**Comment by justinspencer** [comment]
I think this is how we need to communicate the typography system in the GUI Docs. I'm tempted to completely remove the heading styles (from the Docs) so designers don't take it literally however I'm not sure what the ramifications will be. Any thoughts?

![type](https://cloud.githubusercontent.com/assets/936597/15529083/b00e08e2-228d-11e6-88ce-0ed01379cda3.png)

**Comment by justinspencer** [comment]
Here's an updated design option. I've removed the references to headings and called the styles "Display Style". I'm trying to remove the mis-conception that there are six fixed heading styles and nothing else as this caused a lot of confusion in AEM particularly when it came to margins and semantic markup.
[Type.pdf](https://github.com/WestpacCXTeam/GUI-source/files/292894/Type.pdf)
