### ISSUE TITLE
margin top and bottom on the p tag

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-source#253]
From what I can see there is currently no margin specified on the p tag. As a result the user agent is using a 1em margin top and bottom. On p text this computes to 14px. Can we apply a top and bottom margin of 0.85717em on the p tag

**Comment by dominikwilkowski** [comment]
I rounded it up to `0.8571428572em` which is then 12px

**Comment by justinspencer** [comment]
Marvellous
