### ISSUE TITLE
The STG logo needs fixing

### ISSUE THREAD

**Issue by dominikwilkowski** [WestpacCXTeam/GUI-source#254]
Prerequisites
-------------

* [ YES ] Can you reproduce the problem in the [testing area of the GUI](http://westpaccxteam.github.io/GUI-source/)?
* [ YES ] Are you running the latest version of the affected module?
* [ YES ] Did you check if the issue already exists ([open](https://github.com/WestpacCXTeam/GUI-source/issues) or
	[closed](https://github.com/WestpacCXTeam/GUI-source/issues?q=is%3Aissue+is%3Aclosed))?

Description
-----------

The STG logo has two paths that have slipped in too deep and need resurfacing.
![screen shot 2016-05-25 at 11 03 31 am](https://cloud.githubusercontent.com/assets/1266923/15526496/d5aa6388-2275-11e6-9636-81338ed49df9.png)

**Expected behavior:**
The dark green paths need to be on top of the light green

**Actual behavior:**
They are hiding behind the light green ones.

**Comment by justinspencer** [comment]
This is fixed in the visual design starter pack. Do you need me to supply updated svg's?
