### ISSUE TITLE
Breadcrumbs: Use arrow rather than forward slash

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-source#256]
The reason for this is because we now have to use an underline in text links (for accessibility). Underline text is harder to read and doesn't look great so the arrows are a better option when using breadcrumbs. Design will be the same as AEM breadcrumbs.

**Comment by jonnystening** [comment]
@justinspencer which of these arrow symbols are you wanting to use?

›
»
→
>
or SVG?

The Westpac site uses custom SVG icons (https://www.westpac.com.au/personal-banking/bank-accounts/transaction/). This red one is not currently part of the GUI.
