### ISSUE TITLE
Tabcordion- Screen Reader does not recognise which tab is currently activated in Tabcordion

### ISSUE THREAD

**Issue by dominikwilkowski** [WestpacCXTeam/GUI-source#258]
Prerequisites
-------------

* [ Yes ] Can you reproduce the problem in the [testing area of the GUI](http://westpaccxteam.github.io/GUI-source/)?
* [ Yes ] Are you running the latest version of the affected module?
* [ Yes ] Did you check if the issue already exists ([open](https://github.com/WestpacCXTeam/GUI-source/issues) or
	[closed](https://github.com/WestpacCXTeam/GUI-source/issues? q=is%3Aissue+is%3Aclosed))?

Description
-----------

Tabcordion- NVDA does not recognise which tab is currently activated in Tabcordion

Steps to Reproduce
------------------

1. Go to the browser and hit the URLs
2. Check for the tabcordion component in the page
3. Check whether the tabs are read by the NVDA screen reader and whether the currently active tab is mentioned specifically as "Activated/Visited/Selected" to assist the user better

**Expected behavior:**
NVDA screen reader must recognise and explicitly read out the currently activated tab in the tabcordion to the user

**Actual behavior:**
Tabcordion- NVDA does not recognise which tab is currently activated in Tabcordion

Versions
--------

v2.0.0

Screenshots
-----------

![image](https://cloud.githubusercontent.com/assets/4056184/15704525/80af5dca-282e-11e6-8028-85f353c2e41b.png)

**Comment by amitjagtap** [comment]
Hi Dom,

Applied following fixes to resolve this issue - 

1. Accordion Markup - 
![image](https://cloud.githubusercontent.com/assets/4056184/15730827/7d5db998-28b3-11e6-804e-f3c13ea874d0.png)

2. Tabcordion - 
![image](https://cloud.githubusercontent.com/assets/4056184/15730848/9b891458-28b3-11e6-9747-53cfd201b772.png)

3. tabcordion.js - 
![image](https://cloud.githubusercontent.com/assets/4056184/15730864/b1624876-28b3-11e6-9843-f4d346f303a8.png)

Cheers!

**Comment by dominikwilkowski** [comment]
Awesome! Thanks for the almost PR @amitjagtap :)
Some stuff I noticed while implementing it:

- `aria-controls` actually points to an ID
- `.parents('.js-collapsible-tab')` has to be removed from the selector so accrodions work too
