### ISSUE TITLE
St.George - buttons with icons

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-source#262]
When used in buttons the Icon colour is not correct (St.George).
The general rule for the colour of icons when used in buttons is that they inherit the colour of the button text. This rule was established when we used the icon font however now we use svg it's a little more convoluted so we can change if required

![screen shot 2016-06-07 at 12 02 08 pm](https://cloud.githubusercontent.com/assets/936597/15843844/8fa4af82-2ca8-11e6-9a93-357daa16cdd8.png)

**Comment by dominikwilkowski** [comment]
Sorry for the confusion. This is only a test-line for icons that are NOT embedded to test spacing. This is not being advertised and should always be embedded. :)
