### ISSUE TITLE
More color options for badges

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-source#266]
Badges are being used a lot more in native and web apps to highlight new products etc. Would be good to add some accessible color variations. Should probably do the same thing with labels.
Please note the text in the badges:
font-size: 14px;
font-weight: 500;
![screen shot 2016-06-20 at 11 49 27 pm](https://cloud.githubusercontent.com/assets/936597/16196545/c2600d7e-3741-11e6-83aa-d1374327f322.png)

**Comment by diced-dev** [comment]
Colour variations for badges and labels have been added, just need to be reviewed.

@justinspencer I left the font weight for badges at 700, 500 seemed much too light. Check it out, I can drop the font weight if needed.
