### ISSUE TITLE
Display text sizes

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-source#277]
I've added 6 Display sizes to the type system ranging from 48px to 18px. The idea is to give designers more flexibility with heading sizes etc. It also allows designers to choose which font (brand or body) to assign to the heading and the font weight. 300, 400, 500 or 700.

The Display styles already exist in the GUI docs however the sizes need to be adjusted and if possible we should move away from .h1 .h2 classes as this is causing confusion.

We should also look at responsive sizes for the larger headings.

Happy to discuss

**Comment by dominikwilkowski** [comment]
The display sizes are more of a system and are helpful for designers to decide what size something is. We can't implement classes or other helps here as the attributes are too small.
We would end up doing something like `size-1 weight-2 bodyfont` as a class stack which computes to three styles only. Having classes for just one attribute is less than helpful in CSS and just boats the CSS.

However I think the system is great and we should look into how we communicate it in the docs. Perhaps a table?

**Comment by justinspencer** [comment]
After huge debate we've made a decision to remove the display styles (.h1 – .h6)
The reason for this is because every project is overriding the heading styles to suit their individual needs. **IMPORTANT:** Designers still need to use the correct type sizes, font face (brand or body) and font weights provided in the GUI Docs. How they apply these 3 attributes is their call. Obviously designers will need to be aligned with the brand guidelines.
