### ISSUE TITLE
Create a single collapsible accordion - A Collapsion

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-source#287]
Several people have requested the ability to use a single item accordion menu. Technically this would no longer be an "accordion". So may I suggest we create a new element called... A Collapsion.

See screen grab attached...

![collapsion](https://cloud.githubusercontent.com/assets/936597/20122277/b4f6da8a-a66a-11e6-8b94-55b653ef7f0b.png)

**Comment by justinspencer** [comment]
Having spoken to Dom it seems you can do this with the existing component however this is not documented in the GUI Docs. So this may just be a case of adding an example in Docs.

**Comment by diced-dev** [comment]
Ended up requiring some modification to the tabcordion scripts, this enhancement will only work for the soft accordion.
