### ISSUE TITLE
GUI module test pages not responsive on mobile devices

### ISSUE THREAD

**Issue by diced-dev** [WestpacCXTeam/GUI-source#290]
Description
-----------

When viewing the GUI module test pages on mobile devices or within device preview on Chrome the page is not responsive. 

Steps to Reproduce
------------------

1. Load any of the module example pages on a mobile device or within device preview on Chrome.

**Expected behavior:**
The pages should be responsive at all viewport sizes.

**Actual behavior:**
They're not responsive at all viewport sizes.

Versions
--------

All versions.

Fix
--------

Can be fixed by adding viewport meta tag in head of example pages:
`<meta name=viewport content="width=device-width, initial-scale=1">`

The above would need to be applied across all modules.

**Comment by justinspencer** [comment]
I think we need to do this for testing purposes. Testing modules on mobile devices using the GUI Docs can get confusing as the docs uses iFrames which is adding another layer of complexity.

**Comment by dominikwilkowski** [comment]
you should be testing them in isolation in each individual repo.

Like for badges in BOM: http://westpaccxteam.github.io/GUI-badges/tests/BOM/
etc

**Comment by diced-dev** [comment]
Rolled out change to fix this.
