### ISSUE TITLE
Add social media icons to symbols module

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-source#294]
For legal reasons we have to use the correct versions of social media icons. Can we add our colour social media icons to the symbols module?

I've attached svg's for:
Facebook
Google+
Linkedin
Twitter
YouTube.

They will need cleaning up.

[social-icons.zip](https://github.com/WestpacCXTeam/GUI-source/files/630178/social-icons.zip)

**Comment by diced-dev** [comment]
@justinspencer Should I also remove these from [gui-icons-group12](https://gel.westpacgroup.com.au/GUI/WBC/icons#icons-group12)?

**Comment by justinspencer** [comment]
No please leave these in for now.
