### ISSUE TITLE
2 copies of each Symbol SVG when adding GUI-symbols > Symbols to Blend

### ISSUE THREAD

**Issue by diced-dev** [WestpacCXTeam/GUI-source#302]
Description
-----------
Noticed while testing the latest docs update that when adding GUI-symbols > Symbols to a blend (any brand or version of symbols) and selecting to include SVGs in the output, that 2 copies of each SVG is being added to the output zip. 

On extraction from the zip the OS recognises the duplicates and will ask to overwrite one of each SVG.

The blend project installs and runs fine, and none of the output appears broken in any way, it's just a weird bug that should be looked into and resolved.

Steps to Reproduce
------------------
1. Go to [Blender](https://gel.westpacgroup.com.au/GUI/BT/blender/) of any brand.
2. Add Symbols > Symbols to your blend, any version of the module as it happens with all.
3. Blend and look at the output zip in the `GUI-blend/source/svgs` directory, there should be duplicates of the SVGs.

**Comment by jonnystening** [comment]
On OSX you don't get the prompt about overwriting, so this is easy to miss. I can see the dups by reviewing the archive contents using an app like Pacifist. This is a problem. It means if downloading source files and re-running `Grunt` it's going to produce incorrect icon output.

I'm seeing up to three copies of a number of SVG files (facebook.svg, google-plus.svg, youtube.svg etc). One SVG file for the icon (grey), and two files for each of the symbols (coloured).

Plan of attack...
1. Work out why there are two copies of every symbol
2. Find a way to separate icon and symbol SVG files (maybe `/svg/icons` and `/svg/symbols` ?)

**Comment by jonnystening** [comment]
From Symbols v2.0.0 onwards it starts duplicating `/source/svg/*.svg` files

**Comment by jonnystening** [comment]
One copy is pre the [Filename] replace task has run, the other is post the replace task. 

Boom!

[american-express.zip](https://github.com/WestpacCXTeam/GUI-source/files/1137878/american-express.zip)

**Comment by jonnystening** [comment]
fixed bug introduced by  WestpacCXTeam/blender@52a2d9087d1be44efb95bbc60b10154129cb3d25

**Comment by jonnystening** [comment]
New issue opened to tackle part 2. of above (separating icon and symbol SVGs) https://github.com/WestpacCXTeam/GUI-source/issues/349
