### ISSUE TITLE
Brand Logo variations

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-source#305]
We're getting an increasing number of requests for logo variations in the GUI. Each of our brands has multiple logo treatments - Horizontal, stacked, reversed etc. Managing this could get a little out of control. Any thoughts?

**Comment by dominikwilkowski** [comment]
put 'em into the logos module?

**Comment by jonnystening** [comment]
Where are we with this @justinspencer? Do you have some logo variations for me to add?

**Comment by justinspencer** [comment]
I have them but not as svg. Soon

**Comment by justinspencer** [comment]
Close this for now. Logos keep changing and updating.
