### ISSUE TITLE
Update the MasterCard logo

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-source#307]
MasterCard have released a new logo. There are now several variations. I will supply svg's for each of the variations.

**Comment by diced-dev** [comment]
@justinspencer can you attach the new logo file?

**Comment by justinspencer** [comment]
I've added svg's for the required Mastercard logos 
[Mastercard-logos.zip](https://github.com/WestpacCXTeam/GUI-source/files/911830/Mastercard-logos.zip)

**Comment by diced-dev** [comment]
@justinspencer can you attach the new google play logo too?

**Comment by diced-dev** [comment]
@justinspencer never mind, saw the other ticket!

**Comment by imakewebsites** [comment]
Nb. In v2.0.5 class naming reverted back to (dashed) `.symbol-master-card` and `.symbol-master-card-*` format (as opposed to `.symbol-mastercard` and `.symbol-mastercard-*`
