### ISSUE TITLE
Add btn-soft dropdown in docs

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-source#308]
Need to add examples of the btn-soft dropdown in the docs. People don't know this variation exists.

**Comment by imakewebsites** [comment]
@diced-dev I need to get you to show me how to update the symbols sheets (grunticon output) used by a module's _example site (iFrame). Is this updated manually?

**Comment by imakewebsites** [comment]
fixed by WestpacCXTeam/GUI-docs/040c70bff77716b7b5f3763e947ac5a353c6cc65 and WestpacCXTeam/GUI-docs/2fe86ed1f8793f5f3efd1e73acbcbc1b1a621bc0
