### ISSUE TITLE
Change Panel footer background colour

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-source#310]
Please use @color-light for the panel-footer background colour.
It currently uses @color-Backgroud

**Comment by nadia39** [comment]
Hi, I can work on this issue, is it still open?
I need to contribute to open source projects for a class.

**Comment by diced-dev** [comment]
Hi @nadia39, you're welcome to work on this and submit a PR with your change. Just be aware that we we have very little time to provide feedback or answer questions.
