### ISSUE TITLE
Docs - Responsive embeds not previewing

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-source#312]
Responsive embeds are not showing in the docs. All working in the GUI source.

https://gel.westpacgroup.com.au/GUI/STG/media/#responsive-embeds

**Comment by diced-dev** [comment]
@justinspencer This will require a nginx config update to fix, basically it currently only supports the gui domain as an acceptable source for iframes, but the Youtube embed uses an iframe as well and its source is https://www.youtube.com, so it's being blocked.

I just just need to change the Content Security Policy to the following:
`# Content Security Policy
add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' data: https://ssl.google-analytics.com https://cdn.polyfill.io https://www.gstatic.com; img-src 'self' data: https://ssl.google-analytics.com; connect-src 'self'; style-src 'self' 'unsafe-inline' https://www.gstatic.com; font-src 'self'; frame-src 'self' https://www.youtube.com; object-src 'none'";`

**Comment by dominikwilkowski** [comment]
Remember the config is here: https://github.com/WestpacCXTeam/nginx-config
Make sure you save changes there

**Comment by diced-dev** [comment]
@dominikwilkowski Yeah mate, already on it

**Comment by dominikwilkowski** [comment]
it should all just work. When in doubt just restart and everything will be restarted automatically :)

**Comment by diced-dev** [comment]
Config updated, nginx restarted, the world is still turning. Done!
