### ISSUE TITLE
Badges -  wrong height

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-source#318]
Badges are currently 22px high. Need to be 24px.
Please add 1px top and bottom padding to .badge class.

**Comment by diced-dev** [comment]
Changing the padding on these is breaking the alignment of the badge within buttons. We've discussed it and have decided to leave this change for now.

**Comment by imakewebsites** [comment]
Reopened for the backlog

**Comment by jonnystening** [comment]
http://westpaccxteam.github.io/GUI-badges/tests/WBC/
