### ISSUE TITLE
Grid: Change max width and medium breakpoint

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-source#319]
In the grid module please can we investigate changing the max-width of container and container-fluid to 1224px. I'd also like to change the Medium breakpoint (currently 992px) to 996px. As with the other breakpoints using a multiple of 6 makes it much easier to establish grid widths in design files. These changes should also be applied to the GUI Demo screen as this is a great way to see the grid in action. The GUI demo screen currently uses a max-width of 1524px however this is proving to be too wide. Reducing it to 1224px will provide a solid example showing the correct use of the grid.

**Comment by imakewebsites** [comment]
Worth mentioning, the GUI doesn't control the page wrapping element and its padding. This padding (which changes across breakpoints) directly affects the grid layout. Unless every site uses the same page wrapping CSS, the grid will be inconsistent across sites.

**Comment by jonnystening** [comment]
Our final solution here was to

1. Add edge padding on the container elements (`.container` and `.container-fluid`), per breakpoint, providing breathing room against the viewport edge.
2. Set a max width on the fluid container
3. Uncompress the Less, bring back some Bootstrap v3 mixins to help us build the grid CSS; use variables to maintain settings.

These will play nicely with the future template module, which includes header, (sticky) footer and a page wrapper for uber large monitors.

**Comment by jonnystening** [comment]
fixed by WestpacCXTeam/GUI_grid@da9d23b851abb0b8c1c07282f911cb340da5c91e
