### ISSUE TITLE
Colors: Add a heading colour to the core palette

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-source#320]
A couple of developers have raised an interesting concern around specifying the colour of headings when building multi-brand applications. They have requested a "Heading" colour to be added to the core palette. This would give us flexibility and reduce the amount of work with over-rides. For example Hero colour is often used for headings however St.Geroge Hero is not accessible so developers have to account for this using an over-ride. Open for discussion.

**Comment by mpcat** [comment]
Can you bring this up in stand up next week when ash is in?

Sent from my Windows Phone
________________________________

**Comment by jonnystening** [comment]
closed by WestpacCXTeam/GUI_colors/0bbeed625743baca175bdeb1499495df6c6aacbe, WestpacCXTeam/GUI_text-styling/66fe09678826a33cc5d5051cdb44e883153b9b24 and WestpacCXTeam/GUI-docs/2ac92b5d87887c65206064aef912ee48c5ec4f4e
