### ISSUE TITLE
Colors: St.George secondary colour palette updates

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-source#321]
St.George are in the process of a brand refresh. As a result we need to adjust the secondary palette. At this stage the core palette will not be changing. Please see me for more instruction.

**Comment by justinspencer** [comment]
Here are the required changes:
1. Remove Citrus and Spring from the palette
2. Typo - Change Ember to Amber
3. Typo - Change Plumb to Plum
4. Change Amber HEX value to: #FF7F29
5. Remove neutral tints

**Comment by jonnystening** [comment]
closed by WestpacCXTeam/GUI-docs@2ac92b5d87887c65206064aef912ee48c5ec4f4e
