### ISSUE TITLE
Docs: Westpac 200 logo

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-source#326]
Add 200 logo to the GUI. Please see me for position etc.

**Comment by justinspencer** [comment]
This issue corresponds with issue #333. We're going to wait for the next release to make this update as project Simple is currently in build and we don't want to disrupt their workflow.
When we make this update each of the GUI's will use a logo from the Symbols module. This logo will need to be positioned for each brand as we won't be using the standard size for all. See issue #333

**Comment by jonnystening** [comment]
Will be in the November release
