### ISSUE TITLE
Docs - Typography markup error

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-source#328]
Got some markup showing in the docs typography page. See attached image.
<img width="765" alt="screen shot 2017-05-21 at 11 22 18 pm" src="https://cloud.githubusercontent.com/assets/936597/26381814/c458bf3a-406a-11e7-9055-2948e5c91eb1.png">

**Comment by imakewebsites** [comment]
Funnily enough `<snap>Sans serif system font</span>` isn't valid markup

**Comment by imakewebsites** [comment]
fixed by d104e3da75ce751237c6be5a40eb9e8a5f024b13
