### ISSUE TITLE
Colors: Updates to the Primary Colour palette

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-source#332]
This is big and scary.

Complementary A and Complementary B are causing confusion when it comes to designing multi-brand. These colours need to be removed from the primary palette and put into the additional colours. We also need to add a colour to the Primary palette for headings. Doing this will mean that every colour in the primary palette has a purpose and will map correctly when switching brands.

**Comment by justinspencer** [comment]
So Jonny and I have been taking a closer look at this. Some of the brands still need to display Comp A and Comp B as these colours are part of the brand palette. However Comp A and Comp B are never used in the GUI elements. So rather than removing these colours we should perhaps move them to the secondary palette of each brand. The secondary palette is a bespoke collection of colours that do not map per brand. Secondary colours are used for brand specific embellishment and require bespoke application.

**Comment by KateMacdonald** [comment]
Agree



Kate MacDonald
Senior Design Manager, Experience Design & Delivery

W 0435 409 891
ktmacdonald@westpac.com.au

Westpac Group
L22, Tower 2 Barangaroo Ave
Barangaroo NSW 2000 Australia


-------- Original message --------

**Comment by jonnystening** [comment]
closed by WestpacCXTeam/GUI-docs@2ac92b5d87887c65206064aef912ee48c5ec4f4e, WestpacCXTeam/GUI_colors@66d251db75c82417a1e50f2bdbeeedea3f1e64d2 and WestpacCXTeam/GUI_text-styling@63dfecf7ec5c86fa5f15dccfd685b154b4eb8100

**Comment by justinspencer** [comment]
I've written some description text for Docs - Color - Secondary Palette:

**Secondary Palette**
The secondary palette is a collection of bespoke, brand specific colours. Unlike the primary palette these colours do not map to the other brands. Secondary colours are generally used for brand embellishment: info graphics, charts, diagrams etc. They are unique to the brand and must not be used anywhere else.
