### ISSUE TITLE
Remove 3 logos from the Symbols module

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-source#333]
The 3 brand specific logos currently in the Symbols module are causing confusion and adding additional work when updating the GUI. They are...
.symbol .symbol-logo-alt
.symbol .symbol-logo-phone
.symbol .symbol-logo-tablet
These logos were originally designed to make life easier for developers when switching brands as they all use the exact same dimensions. Over time we have seen a decline in their usage. Moving forward I'd like to create several multi-brand, responsive header components which use the icons in the icon module.
Removing the icons should mean the Symbols module becomes a global module so we only need to update 1 instance.

**Comment by justinspencer** [comment]
So it looks like Simple is using the these logos and include them in the symbols module.

**Comment by jonnystening** [comment]
We're proposing to move these three brand logos to a new mobile called `logos-multibrand`. The `symbols` module will be then simplified to a collection of symbols shared across all brands.

**Comment by jonnystening** [comment]
- [ ] Create new `GUI-logos-multibrand` module
- [ ] Bring these three logo SVGs across from symbols (per brand)
- [ ] Tests files generated
- [ ] Files committed and merged to master
- [ ]  GUI-source submodules updated
- [ ] Blender updated
- [ ] Deployed and tested

**Comment by jonnystening** [comment]
fixed by WestpacCXTeam/GUI-symbols@5a5bb97a01cd4800b5c86a822896d352a0bb89f1
