### ISSUE TITLE
Docs: Wrong example name in Containers

### ISSUE THREAD

**Issue by KateMacdonald** [WestpacCXTeam/GUI-source#334]
In docs the first Panel name is 'Primary' panel, it should be 'Hero' - as it uses the 'Hero' colour.

Just a little one.

**Comment by jonnystening** [comment]
@KateMacdonald How about calling that option 'Basic panel'? Showing it's the base styling option (without modifiers), as with default buttons (labelled 'Basic buttons')?

**Comment by jonnystening** [comment]
Lets discuss with @justinspencer

**Comment by jonnystening** [comment]
We're renaming this simply 'Panel' for now, and will look at it again when we come to https://github.com/WestpacCXTeam/GUI-source/issues/347
