### ISSUE TITLE
GUI/library alignment - Lego accordions

### ISSUE THREAD

**Issue by KateMacdonald** [WestpacCXTeam/GUI-source#344]
There are some styling differences between the new Sketch library version of lego accordions and the current examples in the GUI - does the GUI have to be updated?

**Comment by jonnystening** [comment]
... this one too @justinspencer

**Comment by justinspencer** [comment]
I did a lot of work on this with Ash. Styling looks the same to me. What are the differences @KateMacdonald

**Comment by jonnystening** [comment]
@KateMacdonald? 🤔

**Comment by KateMacdonald** [comment]
I think this can be closed - I think I saw something that was not actually there.

**Comment by jonnystening** [comment]
Sounds good
