### ISSUE TITLE
GUI/library alignment - Lists

### ISSUE THREAD

**Issue by KateMacdonald** [WestpacCXTeam/GUI-source#345]
There are some styling differences between the new Sketch library version of lists and the current examples in the GUI - does the GUI have to be updated?

The tick list is using a simple tick icon - should it be added as an icon?

**Comment by jonnystening** [comment]
Can we discuss this J man? @justinspencer

**Comment by justinspencer** [comment]
Good spot. I need to provide the updated tick icon if we think this is the right thing to do. A few people have mentioned that the current tick looks a bit clip art

**Comment by jonnystening** [comment]
@justinspencer is this coming as part of the Icon refresh?
