### ISSUE TITLE
The indicator on the popover needs to be smaller to match Sketch version

### ISSUE THREAD

**Issue by KateMacdonald** [WestpacCXTeam/GUI-source#357]
Align the GUI version of the Popover module - the indicator arrow needs to be smaller

![image](https://user-images.githubusercontent.com/6667337/28297947-e6dbe27a-6bb3-11e7-8b99-656899f0cc22.png)

**Comment by jonnystening** [comment]
I'll crack open @justinspencer's UI Kit for a look see 🕵️
