### ISSUE TITLE
Change text size in dropdown list example

### ISSUE THREAD

**Issue by KateMacdonald** [WestpacCXTeam/GUI-source#358]
There is some very small text at the bottom of the dropdown list examples in 'Dropdown sizing'  - too small for accessibility.  Remove small tag.

**Comment by jonnystening** [comment]
Assuming it's there as a guide for what to use if you need to add additional/supporting footnote text to a dropdown. By removing it are we saying that dropdowns no longer support this kind of text?

`<small>` and `<p>` 'footnote' examples below...

![Uploading para.png…]()
![small](https://user-images.githubusercontent.com/2049709/30040355-976ea90e-9221-11e7-8867-9da990db49d1.png)

**Comment by KateMacdonald** [comment]
Keep the text - just not so small (14px is the smallest we should recommend)
