### ISSUE TITLE
The heading for this module is not correct.

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-source#362]
It should say Popup. Popovers defines all elements that float over content (floaters so to speak).
https://gel.westpacgroup.com.au/GUI/WBC/popovers/#popovers
![screen shot 2017-07-20 at 3 57 33 pm](https://user-images.githubusercontent.com/936597/28402632-3192f3a6-6d64-11e7-8ffc-9a2c7bf444d4.png)

**Comment by jonnystening** [comment]
This module has always been 'Popovers'. I agree with you it's hella confusing, but this will likely cause some backwards incompatibility if we rename it.

@justinspencer

**Comment by justinspencer** [comment]
Fair enough. I'll close it.
