### ISSUE TITLE
Add Form dropdown add-on 

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-source#363]
Dain Saxon has raised an interesting issue/request for another input add-on element.
It's an input field dropdown add-on. See mockup attached.
This pattern is often used for things like selecting fonts etc. The user can either enter the value manually or select from a range of pre-defined values.

![screen shot 2017-07-24 at 12 40 00 pm](https://user-images.githubusercontent.com/936597/28506320-de0ecd10-706d-11e7-926a-6cfc7c4b8306.png)

**Comment by jonnystening** [comment]
Arrrr... a combo box 👍 

Does it perform a typeahead? https://twitter.github.io/typeahead.js/

@justinspencer let's discuss

**Comment by justinspencer** [comment]
This is a useful patten but I'm closing this issue for now as no other designers have requested it and we have to prioritise our work.
