### ISSUE TITLE
Various issues with a fresh blend in a fairly vanilla project

### ISSUE THREAD

**Issue by Imamadmad** [WestpacCXTeam/GUI-source#368]
Various issues:
1)  Tabbed containers don't seem to work out of the box. Have to roll my own JS, which means it doesn't get all the accessibility goodness. Using Lego Tabs in a fresh blend.
2)  Doesn't seem to be any outline on the toggle switches when tabbed to. There is no indication they have been focussed.
3)  No style available for input[type=file].
4)  Dependencies don't download with blended elements. EG: Blending alerts doesn't blend the required icons. In fact, there's no dependency information that I can see.

All observations from a blend made last week. Using IE11. 

The elements are all being used without much CSS/JS to interfere as it's a small, flask-based app.

**Comment by jonnystening** [comment]
Hi @Imamadmad I'm sorry you're having issues. I'll get back to you by COB tomorrow

**Comment by Imamadmad** [comment]
Hi there, just wondering if there's any comment/response to this? These bugs aren't vital, given it's just a small internal app and I've already rolled my own JS for the tabs, but it would be nice to either have these problems fixed (including knowing if it's on the radar to be fixed) or know that they won't be fixed so I can work around it.

**Comment by jonnystening** [comment]
Sorry for the delay @Imamadmad, only getting to this now.

1. I have just checked Tabcordions which seem to be working as per our docs at https://gel.westpacgroup.com.au/GUI/WBC/containers/#tabcordions. A number of the GUI modules require JS (and the jQuery library). Have you included jQuery in your blend? Are you using the correct markup? e.g...
```
<div class="tabcordion tabcordion-lego tabcordion-tabs">
  <ul class="tabcordion-tabs">
    <li class="tabcordion-tab js-collapsible-tab is-active">
      <a class="js-collapsible" href="#ex3-tab1">
        Rabbit hole
        <span class="tabcordion-tab-helper" aria-hidden="true">
          Use the arrow keys to select a tab.
        </span>
      </a>
    </li>
    <li class="tabcordion-tab js-collapsible-tab">
      <a class="js-collapsible" href="#ex3-tab2">
        Flamingo
        <span class="tabcordion-tab-helper" aria-hidden="true">
          Use the arrow keys to select a tab.
        </span>
      </a>
    </li>
    <li class="tabcordion-tab js-collapsible-tab">
      <a class="js-collapsible" href="#ex3-tab3">
        Caterpillar
        <span class="tabcordion-tab-helper" aria-hidden="true">
          Use the arrow keys to select a tab.
        </span>
      </a>
    </li>
  </ul>
  <div id="ex3-tab1" class="collapsible-body is-open" aria-hidden="false" tabindex="-1">
    <div class="tabcordion-body">
      &lsquo;It was much pleasanter at home,&rsquo; thought poor Alice, &lsquo;when one wasn&rsquo;t always growing larger and smaller, and being ordered
      about by mice and rabbits. I almost wish I hadn&rsquo;t gone down that rabbit-hole — and yet — and yet — it&rsquo;s rather curious, you know, this
      sort of life! I do wonder what can have happened to me! When I used to read fairy-tales, I fancied that kind of thing never happened, and now here
      I am in the middle of one! There ought to be a book written about me, that there ought! And when I grow up, I&rsquo;ll write one.
    </div>
  </div>
  <div id="ex3-tab2" class="collapsible-body" aria-hidden="true" tabindex="-1">
    <div class="tabcordion-body">
      The chief difficulty Alice found at first was in managing her flamingo: she succeeded in getting its body tucked away, comfortably enough, under her
      arm, with its legs hanging down, but generally, just as she had got its neck nicely straightened out, and was going to give the hedgehog a blow with
      its head, it would twist itself round and look up in her face, with such a puzzled expression that she could not help bursting out laughing: and when
      she had got its head down, and was going to begin again, it was very provoking to find that the hedgehog had unrolled itself, and was in the act
      of crawling away: besides all this, there was generally a ridge or furrow in the way wherever she wanted to send the hedgehog to, and, as the
      doubled-up soldiers were always getting up and walking off to other parts of the ground, Alice soon came to the conclusion that it was a very
      difficult game indeed.
    </div>
  </div>
  <div id="ex3-tab3" class="collapsible-body" aria-hidden="true" tabindex="-1">
    <div class="tabcordion-body">
      The Caterpillar and Alice looked at each other for some time in silence: at last the Caterpillar took the hookah out of its mouth, and addressed
      her in a languid, sleepy voice.<br />
      &lsquo;Who are you?&rsquo; said the Caterpillar.<br />
      This was not an encouraging opening for a conversation. Alice replied, rather shyly, &lsquo;I — I hardly know, sir, just at present — at least I
      know who I was when I got up this morning, but I think I must have been changed several times since then.&rsquo;<br />
      &lsquo;What do you mean by that?&rsquo; said the Caterpillar sternly. &lsquo;Explain yourself!&rsquo;<br />
      &lsquo;I can&rsquo;t explain myself, I&rsquo;m afraid, sir&rsquo; said Alice, &rsquo;because I&rsquo;m not myself, you see.&rsquo;<br />
      &lsquo;I don&rsquo;t see,&rsquo; said the Caterpillar.<br />
      &lsquo;I&rsquo;m afraid I can&rsquo;t put it more clearly,&rsquo; Alice replied very politely, &lsquo;for I can&rsquo;t understand it myself to begin
      with; and being so many different sizes in a day is very confusing.&rsquo;
    </div>
  </div>
</div>
```
2. Keyboard tabbing is managed via a tiny bit of JS which switches the GUI to keyboard mode on tab press. The outline CSS styling lives in the `_text-styling` core module.
3. GUI framework doesn't currently style the File Input element. This is likely in a future release.
4. There is currently no automated dependency management. If you want to display Icons within Alerts you will need to make sure you also select the Icons module in your blend as per "For a more friendly look, add an icon but **make sure you have the icon in your blend**." [Alerts](https://gel.westpacgroup.com.au/GUI/WBC/alerts/#alerts)

Hope this helps. Feel free to ping me on [Slack](https://westpac-digital.slack.com/signup) if you would like to discuss.

**Comment by Imamadmad** [comment]
Hi Jonny.

Nowhere in the docs for the tabcordion does it mention having to include jQuery. Similarly, nowhere obvious does it mention needing jQuery to get the tabbing style working right (and in theory it should be able to be achieved with CSS only in significantly more instances than it currently is). I'll try including jQuery when I get back to work on Monday and see if that makes a difference.

Best regards,
~Maddie

**Comment by Imamadmad** [comment]
Hi Jonny. 

I figured out why the icons never loaded on my last project. Googling about Grunticons themselves, I came across the need to include the following snippet of JS in the HTML head:

``<script>
    /* grunticon Stylesheet Loader | https://github.com/filamentgroup/grunticon | (c) 2012 Scott Jehl, Filament Group, Inc. | MIT license. */
    window.grunticon=function(e){if(e&&3===e.length){var t=window,n=!!t.document.createElementNS&&!!t.document.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect&&!!document.implementation.hasFeature("http://www.w3.org/TR/SVG11/feature#Image","1.1"),A=function(A){var o=t.document.createElement("link"),r=t.document.getElementsByTagName("script")[0];o.rel="stylesheet",o.href=e[A&&n?0:A?1:2],r.parentNode.insertBefore(o,r)},o=new t.Image;o.onerror=function(){A(!1)},o.onload=function(){A(1===o.width&&1===o.height)},o.src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw=="}};
    grunticon( [ "icons.data.svg.css", "icons.data.png.css", "icons.fallback.css" ] );
    </script>
    <noscript><link href="icons.fallback.css" rel="stylesheet"></noscript>``

After inserting, it is then necessary to update the paths to the correct files.

I suspect from the fact that this snippet wasn't included in the SVG instructions that it must be somewhere in the gui.min.js file, although I'm not planning on reading minified JS to check. However, if it is, then I would recommend adding instructions somewhere on the SVG page on how to update the paths to be relevant to an individual team's project.

On a different topic, I like the updates you've made to the GEL page with all the extra hints and instructions! Makes getting a blend that much simpler :)

**Comment by jonnystening** [comment]
@Imamadmad the GUI framework uses Grunticon as its SVG icon solution. There is some additional GUI documentation available on each blend's lading page... [Westpac GUI](https://gel.westpacgroup.com.au/GUI/WBC/) and you can read about Grunticon in more detail at https://github.com/filamentgroup/grunticon. You will need to include the minified loader JS inline within your document `<head>`. 

We have a number of improvements we hope to bring you during the year. If you have any suggestions please send them through.

Thanks for your feedback!

**Comment by Imamadmad** [comment]
Hi @jonnystening . Thanks for pointing the way. It's good the information is there somewhere, but a just-in-time reminder on the icons page itself will help greatly with usability.

I was going to open this in a new issue, but it's related to the concept of not being able to find enough instructions, so I may as well do it here.

When implementing the tabs, I can call `GUI.tabcordion.init();` within my ready function block to get the tabs working in Chrome. This however doesn't seem to be enough for IE11. Is there anything more that is needed to enable to tabcordions other than that code line? If not, can I send a link to this project's BitBucket via your internal email for some troubleshooting?

**Comment by Imamadmad** [comment]
Hi @jonnystening . Thanks for pointing the way. However, a just-in-time reminder on the icons page, as you've implemented with so many of the other pages over the past half-year, would be great for usability.

A suggestion: Since all items such as tabcordions are initialised the same way on page ready, would it be possible to do that step in the included JS download? Makes things easier to plug-and-play if all a person has to do is add the HTML snippet and have the JS work instantly as the CSS does. That's what I was assuming was supposed to happen when I was getting annoyed about the tabs not working those months ago.

Thanks for all your help and feedback :)
