### ISSUE TITLE
Feature Request: Native React Classes

### ISSUE THREAD

**Issue by rorychatterton** [WestpacCXTeam/GUI-source#369]
Prerequisites
-------------
N/A

Description
-----------
With WDP likely to pickup React for the UI as a Service portion, it would be useful to start providing native React Classes for importing into web projects.

Similar has been accomplished with   [React-Bootstrap](https://github.com/react-bootstrap/react-bootstrap)

Is this something that the WestpacCXTeam would be interested in working on in the future?

As the Gel references are so close to Bootstrap3, it's possible you can fork react-bootstrap and add in any missing classes.

Steps to Reproduce
------------------
N/A

Versions
--------
N/A 

Screenshots
-----------

**Comment by jonnystening** [comment]
Hi @rorychatt, I like your thinking lets have a chat offline when you're free. I'll flick you an email later today.
