### ISSUE TITLE
Input addons with select - text looks too low

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-source#371]
See attached. Need to ensure that adjusting this doesn't break the text alignment in any other button style.
![screen shot 2017-08-21 at 3 47 32 pm](https://user-images.githubusercontent.com/936597/29505410-80f46716-8689-11e7-8482-77cbec0c7fdd.png)

**Comment by jonnystening** [comment]
fixed by WestpacCXTeam/GUI-input-groups@6d312e2338e89e2a94d746125c98b61623149392

(nb. The Input Addons module is now deprecated, styling merged into Input Groups Module WestpacCXTeam/GUI-input-addons@317677d2d4c99cdcee4e901fd3618de18056dd43)
