### ISSUE TITLE
BT code in GUI

### ISSUE THREAD

**Issue by jonnystening** [WestpacCXTeam/GUI-source#372]
Our BT GUI is for 'BT Financial Group'. Are we going to have another BT division join the fray at some point? Is there such a thing (maybe BT is simply BT)?

I'm thinking the BT code should have maybe been `BTFG` or `BTF`.

Just documenting it here for discussion

**Comment by mpcat** [comment]
BT Retail have their own crew. Would be good to catch up with them and share ideas though...see what they are up to

Sent from my Windows 10 phone

**Comment by jonnystening** [comment]
The 'BT' brand code will change to 'BTFG' in the September release

**Comment by jonnystening** [comment]
After having a go with the above, turns out of course we can't edit references to BT within legacy module versions. 

Closing this off as it's not possible with the current GUI build structure.
