### ISSUE TITLE
Button icon gap

### ISSUE THREAD

**Issue by jonnystening** [WestpacCXTeam/GUI-source#378]
Left and Right options seem to have a different gap width (3px vs 12px)

Is this intentional?

**Comment by jonnystening** [comment]
fixed by WestpacCXTeam/GUI-buttons@6b9b3e8faed152ebedfd61fdef7005c3e1badfc8

**Comment by jonnystening** [comment]
https://westpaccxteam.github.io/GUI-buttons/tests/WBC/

**Comment by justinspencer** [comment]
Looks good. Just need to test on IE and Android.

**Comment by justinspencer** [comment]
Back arrow is not the right size in sm up.
