### ISSUE TITLE
Module sizing options

### ISSUE THREAD

**Issue by jonnystening** [WestpacCXTeam/GUI-source#380]
We’re bringing in a new consistent classing convention going forward... `.module-[xsmall|small|large|xlarge]` to denote appearance sizing and `[xs|sm|md|lg|xl]` to denote breakpoint. That way we won’t have uber confusing class names like `.btn-sm-sm`. This example would be `.btn-small-sm`, meaning "button is sized small at the `sm` breakpoint".

('medium' will be the default size and **not** explicitly required via a '.btn-medium' class)

This new naming approach will affect buttons, icons, modals etc. We will update the Icons module to begin with (as part of https://github.com/WestpacCXTeam/GUI-source/issues/360), also referenced by Alerts and Buttons (as icons can be placed in either).

The following modules will need updating to utilise this new naming convention...

- [x] Icons
- [x] Buttons
- [x] Input Addons
- [x] Input Fields
- [x] Input Groups
- [x] Modals
- [x] Switches
- [x] Badges (buttons)
- [x] Alerts (icons)
- [x] Symbols
- [x] Tooltips (icons)

Docs will also need to be updated as per https://github.com/WestpacCXTeam/GUI-source/issues/223

**Comment by jonnystening** [comment]
Closed by a number of commits. Love to link you through to them all, but nah soz.

**Comment by justinspencer** [comment]
I'm assuming Input Addons is now Input Groups

**Comment by justinspencer** [comment]
Alerts close icon. Please use the contextual colour. For example the info close icon is blue. See Sketch file for reference.

**Comment by justinspencer** [comment]
Alerts select menu. The caret is missing.

**Comment by jonnystening** [comment]
@justinspencer caret was only missing on the testing page, was all good, but now fixed
