### ISSUE TITLE
New Headers & Footers modules

### ISSUE THREAD

**Issue by jonnystening** [WestpacCXTeam/GUI-source#381]
Build out two new modules... GUI-headers and GUI-footers

These modules/components will utilise elements from GUI-logos (v2.0.6), GUI-buttons (v4.0.0) and GUI-icons (v2.0.0)

[Forms-Header.sketch.zip](https://github.com/WestpacCXTeam/GUI-source/files/1301275/Forms-Header.sketch.zip)

**Comment by jonnystening** [comment]
closed by WestpacCXTeam/GUI-headers, WestpacCXTeam/GUI-footers

**Comment by jonnystening** [comment]
https://westpaccxteam.github.io/GUI-headers/tests/WBC/
https://westpaccxteam.github.io/GUI-footers/tests/WBC/

**Comment by justinspencer** [comment]
header-basic Padding left and right needs adjusting: 12px XS and 24px SM up
This also means that negative margin on the back arrow should change to -12px and -24px

**Comment by jonnystening** [comment]
These is now all tickidy boo. Please re check.

https://westpaccxteam.github.io/GUI-headers/tests/WBC/
https://westpaccxteam.github.io/GUI-footers/tests/WBC/

**Comment by justinspencer** [comment]
Tested in Chrome and Safari and iOS. All good.
