### ISSUE TITLE
Simplify Icons within Buttons

### ISSUE THREAD

**Issue by jonnystening** [WestpacCXTeam/GUI-source#383]
Button icons shouldn't require `.btn-icon`, `.btn-text` and icon sizing classes. A button (at whatever size) should resize its icon to suit.

Icons should fall on the right by default. Left icon placement (which isn't advised) just placing the icon before text and adding a `.btn-icon-left` modifier on the button.

Block buttons also need updating to match Sketch UI Kit. Text/icon should align with button edge.

**Comment by jonnystening** [comment]
https://westpaccxteam.github.io/GUI-buttons/tests/WBC/

**Comment by justinspencer** [comment]
All looks good in Chrome and Safari on Mac. I'd like to do more testing in IE and Android.

**Comment by justinspencer** [comment]
Button groups hover (small) not working.
![screen shot 2017-09-26 at 2 20 21 pm](https://user-images.githubusercontent.com/936597/30842490-edc49f84-a2c5-11e7-959f-0a168e68a51c.png)

**Comment by jonnystening** [comment]
Fixed that now, also check everything again. You were looking at an out of date link sorry.
