### ISSUE TITLE
Fieldset & Legend styling

### ISSUE THREAD

**Issue by jonnystening** [WestpacCXTeam/GUI-source#386]
Fieldsets and Legends need to be styled

Refer to Input Fields test page http://westpaccxteam.github.io/GUI-input-fields/tests/WBC/ (see "Fieldset" heading)

**Comment by jonnystening** [comment]
Needs your input Mr @justinspencer

**Comment by justinspencer** [comment]
It's probably not wise to style these in isolation. I think we're about to re-visit forms so lets wait until we have a more holistic view of this.

**Comment by jonnystening** [comment]
The custom styling of fieldset and legend elements has been removed as those elements are used exclusively for grouped inputs (radios, checkboxes, and multi text input form patterns such as DOB and Expiry date) in our new accessible forms work.
