### ISSUE TITLE
Tooltip font-size value used is not in the typographic scale

### ISSUE THREAD

**Issue by jannisg** [WestpacCXTeam/GUI-source#389]
Hi,

The current font-size value used in Tooltips is `12px` which is not part of the [typographic scale](https://gel.westpacgroup.com.au/GUI/WBC/typography/) that starts at `14px` as its smallest value. 

https://github.com/WestpacCXTeam/GUI-tooltips/blob/d901fcda9c6316596beabe142c5d0d88658bd6d6/less/module-mixins.less#L90

Should this font-size value be derived from the scale and as such be increased to use the smallest value of the typographic scale which is `14px`?

**Comment by justinspencer** [comment]
Hey Jannis,
I'd like to keep tool tips small and compact. They're not intended to be part of the editorial text and they're not an integral part of a task. We also use 12px text in form validation messaging for the same reason. As these are specific "edge case" scenarios it's not something we want to provide as an option or it could be used incorrectly.
