### ISSUE TITLE
Update the App Store button

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-source#394]
Apple have updated their App Store button slightly. They've also introduced a reversed version.
SVG's for both versions are attached.

[AppStore.zip](https://github.com/WestpacCXTeam/GUI-source/files/1448127/AppStore.zip)

**Comment by jonnystening** [comment]
This will be in the November release

**Comment by jonnystening** [comment]
fixed by WestpacCXTeam/GUI-symbols@95e471cb0d8daa168cea0d04af2edf42332b1fb4
