### ISSUE TITLE
Icon - Add new Pay icon

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-source#395]
See attached.

[pay.zip](https://github.com/WestpacCXTeam/GUI-source/files/1448339/pay.zip)

**Comment by jonnystening** [comment]
Will be in November release

**Comment by jonnystening** [comment]
fixed by WestpacCXTeam/GUI-symbols@95e471cb0d8daa168cea0d04af2edf42332b1fb4

**Comment by jonnystening** [comment]
fixed by WestpacCXTeam/GUI-icons#d49a622e65ab5cbb913e2c52191e2039cec0cc5b
