### ISSUE TITLE
Add new icons

### ISSUE THREAD

**Issue by jonnystening** [WestpacCXTeam/GUI-source#397]
The following icons are to be added:

- [x] gift
- [x] image-square

@justinspencer please flick me the SVGs

**Comment by justinspencer** [comment]
I've attached an svg of the image-square.
[image-square.svg.zip](https://github.com/WestpacCXTeam/GUI-source/files/1486110/image-square.svg.zip)
@KateMacdonald  can you add this to the Axure UI Kit

**Comment by justinspencer** [comment]
Added gift svg
[gift.zip](https://github.com/WestpacCXTeam/GUI-source/files/1489687/gift.zip)
@KateMacdonald can you add this to the Axure UI Kit

**Comment by jonnystening** [comment]
fixed by WestpacCXTeam/GUI-icons@a33070c8d63ae76aa6c8fd6301388a58165fa602
