### ISSUE TITLE
Dismissable popover on touchscreens broken

### ISSUE THREAD

**Issue by jharris-westpac** [WestpacCXTeam/GUI-source#4]
I found an issue on an iPhone Safari iOS8 with the dismissable popovers here http://thewestpacgroup-gel.io/GUI/Westpac/docs/javascript.html#popover 

When you add the class js-popover-dismiss to the button, it stops working entirely on mobile. It works fine for desktop, but I believe all touchscreens are affected. The GEL page above is also affected and does not work on iPhone latest.  

I could not find the dismissable popover on the bootstrap site.

**Comment by dominikwilkowski** [comment]
Thanks James,

I have not yet written this component so I will have a look for it.

**Comment by dominikwilkowski** [comment]
This is fixed in the new component:
http://westpaccxteam.github.io/GUI-source/popovers/1.0.0/tests/STG/

fixed via b82c6dddaf3eba522ba0602888b68557f9d9cf70
