### ISSUE TITLE
GUI docs enhancements

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-source#404]
Few small enhancements to GUI Docs

**Code tabs:**
1. Need to be 42px high.
2. Use expand more icon small (18px). See image attached
**Headings:**
3. Make content h2 and content h3 headings bold. (all brands). See image attached.

![screen shot 2017-12-08 at 10 30 43 am](https://user-images.githubusercontent.com/936597/33744072-960b4230-dc03-11e7-96ff-e4c61e5b561b.png)
![screen shot 2017-12-08 at 10 35 33 am](https://user-images.githubusercontent.com/936597/33744073-963bec8c-dc03-11e7-9de3-929d6f7d6db4.png)

**Comment by jonnystening** [comment]
- [ ] Need to be 42px high.
- [ ] Use expand more icon small (18px). See image attached
- [ ] Headings: Make content h2 and content h3 headings bold. (all brands). See image attached.

**Comment by jonnystening** [comment]
fixed by WestpacCXTeam/GUI-docs@8f8a2cc77e15b683524705729415c53377762389 and WestpacCXTeam/GUI-docs@d20994f121f1f731307c6c5352b0ede2a72963c1
