### ISSUE TITLE
This repo is globally accessible

### ISSUE THREAD

**Issue by perrystephenson** [WestpacCXTeam/GUI-source#411]
Hi everyone,

Someone on Twitter shared the link to this repo, and pointed out that you should probably lock down the security settings a bit. If someone wanted to phish Westpac's customers, you've just given them all of the tools they need to do a really convincing job of it.

Cheers,
Perry

**Comment by Imamadmad** [comment]
Just wanna say, this is such a good front-end framework, and phishers can get everything from exporting the resources from Westpac Live etc anyway, that I would be sad to see it no longer publicly available. I use it as the basis of many of my own projects, changing the basic styling to not look anything like Westpac etc but still benefiting from the UX and accessibility benefits it brings.

I know at the least that the ISG SAS team knows of its public existence and isn't worried, although I don't know about the rest of ISG.

**Comment by jonnystening** [comment]
Hi @perrystephenson 
 
Thanks for taking the time to contact us. We have chosen to make this code available to help facilitate the sharing of design resources with our partners, to communicate our customer centric design maturity and showcase our CX and Design capability. Westpac has robust systems in place to protect sensitive information including source code. This code uses publicly available information and is no way connected with customer data.
 
Kind regards
Jonny
