### ISSUE TITLE
Fancy footer

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-source#412]
Having reviewed the Westpac Basic Footer component we've decided to remove the energy bar divider and use a 1px red line similar to STG, BOM and BSA. This will be the "out of the box" behaviour. The energy bar graphic divider can be added using a modifier class called footer-divider-fancy. This will allow us to use similar approach for the other brands if required.

**Comment by jonnystening** [comment]
fixed by WestpacCXTeam/GUI-footers@ce448b8de6373167e3ffd5efa25442b1f92df1c2
