### ISSUE TITLE
Loading icon size in docs

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-source#415]
Is it possible to increase the size of the animated loading icon in the docs. It is unlikely that this icon would be used at the default size (24px) as this is quite small for a loading animation.

**Comment by jonnystening** [comment]
Add `.icon-xlarge` class to the loading icon example for icons v2.0.0 and v2.0.1

Don't worry about adding this to the text label, it should just say ".icon-loading"
