### ISSUE TITLE
Need to deprecate Input addons

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-source#416]
Although the Input Addons ingredient is now deprecated (merged into Input Groups v3.0.0) people are still seeing Addons in Docs. This is causing some confusion as people are reluctant to read the notes. I've discussed this issue with Jonny and he has updated the deprecated icon page to include any future deprecated modules. This will allow us to remove the deprecated module from Docs which should alleviate the confusion.

**Comment by jonnystening** [comment]
fixed by a single commit to each of the Icon Groups and Input Addons repos
