### ISSUE TITLE
BSA colours

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-source#438]
Need to update the following colours:

Muted: #6A6E72
Neutral: #6A6E72

This will ensure that muted and neutral can be used on background.

**Comment by jonnystening** [comment]
@justinspencer is this still a thing?

**Comment by justinspencer** [comment]
Yes this is still a thing as we now fall out of an accessible range in 2.1. Rather than making Muted and Neutral darker I think it's probably better to lighten Background and Light. I'll close this ticket and create a new one.
