### ISSUE TITLE
Alerts padding to stop text running over the close button

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-source#445]
Since moving to flexbox it seems that we've lost the padding which wraps the first line of text in an alert box so it does not hit the close button.

**Comment by jonnystening** [comment]
Previously we considered the button inline with text, floating right and pulled up and to the right out of the way. This approach meant the button flowed inline with the alert box text and never overlapped the text.

Let's look into why we went with the pos:abs approach when we updated the alert box for the form design patterns. I'm more than happy to revert to the inline approach, as long as we don't break something along the way.

**Comment by jonnystening** [comment]
fixed by WestpacCXTeam/GUI-alerts/98ebfc1d8a0d108ab00ac21e4c65ed2ecee90dae and WestpacCXTeam/GUI-alerts/8fd2140cb8fa1ff391769ed0a2932e3280362ee2
