### ISSUE TITLE
1.1 Color contrast

### ISSUE THREAD

**Issue by dominikwilkowski** [WestpacCXTeam/GUI-source#73]
[1.1](http://maxdesign.com.au/jobs/GUI2.0-accessibility-model-report/#sec1-1)

- [ ] On the Alerts page, the Warning Alert has a Color Contrast ratio of 3.49:1
- [ ] On the Buttons page, the Primary button hover state has a Color Contrast ratio of 3.41:1
- [ ] On the Buttons page, the Primary button active state has a Color Contrast ratio of 2.4:1
- [ ] On the Buttons page, the Hero button hover state has a Color Contrast ratio of 3.01:1
- [ ] On the Buttons page, the Hero button active state has a Color Contrast ratio of 2.1:1
- [ ] On the Buttons page, the Neutral button hover state has a Color Contrast ratio of 2.77:1
- [ ] On the Buttons page, the Neutral button active state has a Color Contrast ratio of 1.99:1

**Comment by justinspencer** [comment]
Fixed the active state on the Warning alert. There is now a new Orange for Warning. See attached.
Re. the remaining hover and active states. They are low priority and out of scope for this release.
![screen shot 2015-07-31 at 2 30 52 pm](https://cloud.githubusercontent.com/assets/936597/9000821/e1c56436-3790-11e5-9265-32310239ab07.png)
