### ISSUE TITLE
Heading 6 Westpac

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-source#8]
14px font-weight 700

**Comment by dominikwilkowski** [comment]
# BOM
| Headline | font-size       | font-weight          |
| -------- | ----------------|--------------------- |
| H1      | XX | XX |
| H2      | XX | XX |
| H3      | XX | XX |
| H4      | XX | XX |
| H5      | XX | XX |
| H6      | XX | XX |

# BSA
| Headline | font-size       | font-weight          |
| -------- | ----------------|--------------------- |
| H1      | XX | XX |
| H2      | XX | XX |
| H3      | XX | XX |
| H4      | XX | XX |
| H5      | XX | XX |
| H6      | XX | XX |

# STG
| Headline | font-size       | font-weight          |
| -------- | ----------------|--------------------- |
| H1      | XX | XX |
| H2      | XX | XX |
| H3      | XX | XX |
| H4      | XX | XX |
| H5      | XX | XX |
| H6      | XX | XX |

# WBC
| Headline | font-size       | font-weight          |
| -------- | ----------------|--------------------- |
| H1      | XX | XX |
| H2      | XX | XX |
| H3      | XX | XX |
| H4      | XX | XX |
| H5      | XX | XX |
| H6      | XX | XX |
