### ISSUE TITLE
Button dropdowns design too similar to selects

### ISSUE THREAD

**Issue by dominikwilkowski** [WestpacCXTeam/GUI-source#96]
The button dropdowns:
![screen shot 2015-07-10 at 11 38 15 am](https://cloud.githubusercontent.com/assets/1266923/8610647/47b7c3fa-26f8-11e5-8733-a2936103ae5b.png)

And the Selects:
![screen shot 2015-07-10 at 11 38 40 am](https://cloud.githubusercontent.com/assets/1266923/8610649/4e06d78c-26f8-11e5-90db-9580623d3e40.png)

Though both function very differently. May need different design. The split-button design would not be appropriate as it suggests a split button with two different functionalities.
![screen shot 2015-07-10 at 11 40 44 am](https://cloud.githubusercontent.com/assets/1266923/8610663/873d1ad4-26f8-11e5-91ac-8c08b2e99c88.png)

**Comment by justinspencer** [comment]
Happy to remove split buttons. Need more explanation around why this is an issue given that select menus use the operating system's drop down visual. Happy to re-design this if necessary but not a priority for v2.0 release.
